version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    depends_on:
      - memcached

  memcached:
    image: memcached:latest
    # container_name: memcached
    # ports:
    #   - "11211:11211"

          